# Generated by Django 4.2.3 on 2023-07-27 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.PositiveBigIntegerField(choices=[(1, 'один'), (2, 'два'), (3, 'три')], verbose_name='количество уровней')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='user_page.user', verbose_name='заказчик')),
            ],
        ),
    ]
