# Generated by Django 4.2.3 on 2023-07-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0003_cake_form_cake_topping_alter_cake_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='berries',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ежевика'), (2, 'малина'), (3, 'голубика'), (4, 'клубника')], default=None, null=True, verbose_name='ягоды'),
        ),
        migrations.AddField(
            model_name='cake',
            name='decor',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'фисташки'), (2, 'безе'), (3, 'фундук'), (4, 'пекан'), (5, 'маршмеллоу'), (6, 'марципан')], default=None, null=True, verbose_name='декор'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='form',
            field=models.PositiveSmallIntegerField(choices=[(1, 'круг'), (2, 'квадрат'), (3, 'прямоугольник')], default=1, verbose_name='форма'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='topping',
            field=models.PositiveSmallIntegerField(choices=[(1, 'без'), (2, 'белый'), (3, 'карамельный'), (4, 'кленовый'), (5, 'черничный'), (6, 'молочный шоколад'), (7, 'клубничный')], default=1, verbose_name='топпинг'),
        ),
    ]
