# Generated by Django 4.2.3 on 2023-07-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0007_remove_order_delivecomments_order_address_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
