# Generated by Django 4.2.3 on 2023-07-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0008_remove_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default=0, max_length=300, verbose_name='адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name='дата доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(default='00:00', verbose_name='время доставки'),
            preserve_default=False,
        ),
    ]
