# Generated by Django 4.2.3 on 2023-07-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0010_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WM', 'Необработанный'), ('WR', 'Ожидание рестарана'), ('WC', 'Ожидание курьера'), ('CL', 'Завершён')], db_index=True, default='WM', max_length=2, verbose_name='статус'),
        ),
    ]
