# Generated by Django 4.2.3 on 2023-07-27 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0011_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='user',
        ),
    ]
