# Generated by Django 4.2.3 on 2023-07-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0013_senderurl_recievedrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recievedrequest',
            name='date',
            field=models.DateTimeField(verbose_name='дата запроса'),
        ),
    ]
