# Generated by Django 4.2.3 on 2023-07-28 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0015_alter_recievedrequest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recievedrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='дата запроса'),
        ),
    ]
